mkdir -p ./data
mkdir -p ./data/config
mkdir -p ./data/event_logs/raw
mkdir -p ./data/event_logs/dataframe
mkdir -p ./data/event_logs/training_data
mkdir -p ./data/event_logs/simulation_df
mkdir -p ./data/logs
mkdir -p ./data/models
mkdir -p ./data/tmp
