from enum import Enum


class MessageType(str, Enum):
    """Enum for message type."""
    ONLINE_REPORT = "ONLINE_REPORT"
    ONLINE_INQUIRY = "ONLINE_INQUIRY"
    TRAINING_DATA = "TRAINING_DATA"
    DATA_RESULT = "DATA_RESULT"
    MODEL_NAME = "MODEL_NAME"
    STREAMING_PREPARE = "STREAMING_PREPARE"
    STREAMING_READY = "STREAMING_READY"
    PRESCRIBE_REQUEST = "PRESCRIBE_REQUEST"
    PRESCRIBE_RESULT = "PRESCRIBE_RESULT"

