from enum import Enum


class MessageType(str, Enum):
    """Enum for message type."""
    ONLINE_INQUIRY = "ONLINE_INQUIRY"
    ONLINE_REPORT = "ONLINE_REPORT"
    TRAINING_DATA = "TRAINING_DATA"
    DATA_REPORT = "DATA_REPORT"
    ERROR_REPORT = "ERROR_REPORT"
    TRAINING_START = "TRAINING_START"
    MODEL_NAME = "MODEL_NAME"
    DATASET_PRESCRIPTION_REQUEST = "DATASET_PRESCRIPTION_REQUEST"
    DATASET_PRESCRIPTION_RESULT = "DATASET_PRESCRIPTION_RESULT"
    STREAMING_PREPARE = "STREAMING_PREPARE"
    STREAMING_READY = "STREAMING_READY"
    STREAMING_PRESCRIPTION_REQUEST = "STREAMING_PRESCRIPTION_REQUEST"
    STREAMING_PRESCRIPTION_RESULT = "STREAMING_PRESCRIPTION_RESULT"
    STREAMING_STOP = "STREAMING_STOP"
